config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions' }
  ActiveAdmin.routes(self)

  root 'books#index'

  resources :order_items, only: %i[create update destroy]
  resources :books, only: %i[show index]
  resources :reviews, only: :create
  resources :orders, only: %i[index show]
  resource :cart, only: :show

  get 'settings' => 'users#edit'
  patch 'settings' => 'users#update'
  patch 'coupons' => 'coupons#update'
  patch 'order_items' => 'order_items#update'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_images, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).or(where(email: auth.info.email)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz')
      user.name = auth.info.name
      user.avatar = auth.info.image
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      @user.send_reset_password_instructions
      set_flash_message(:notice, :success, kind: I18n.t('quick_registration.facebook')) if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  after_action :apply_session_to_order, only: :create

  def create
    super
  end

  def after_sign_in_path_for(_resource)
    current_user.admin ? admin_root_path : root_path
  end

  def apply_session_to_order
    session[:guest_items]&.each do |book_id, quantity|
      CreateOrderItemService.new.call(current_order.id, book_id: book_id, quantity: quantity)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
    @billing_address = current_user.billing_address || BillingForm.new
    @shipping_address = current_user.shipping_address || ShippingForm.new
  end

  def update
    update_avatar if params.include?('new_avatar')
    update_email if params.include?('email_form')
    update_password if params.include?('password_form')
    upload_image if params.include?('upload_image')
    update_address
  end

  private

  def update_avatar
    if params[:new_avatar].present?
      current_user.avatar = current_user.user_images.find_by(id: params[:new_avatar]).image_url
      current_user.save
    end
    redirect_to settings_path
  end

  def update_address
    update_billing_address if params.include?('billing_address')
    update_shipping_address if params.include?('shipping_address')
  end

  def upload_image
    image = current_user.user_images.create(image: params[:upload_image][:image])
    current_user.avatar = image.image_url
    current_user.save
    redirect_to settings_path
  end

  def update_email
    assign_flash(UpdateUserService.new.call(params, current_user), I18n.t('quick_registration.autocomplete_email'))
    redirect_to settings_path
  end

  def update_password
    update_service = UpdateUserService.new.call(params, current_user)
    assign_flash(update_service, I18n.t('settings.password'))
    sign_in(:user, current_user) if update_service
    redirect_to settings_path
  end

  def update_billing_address
    @billing_address = UpdateAddressService.new.call(params, current_user)
    @shipping_address = current_user.shipping_address || ShippingForm.new
    return render :edit unless @billing_address.errors.empty?

    redirect_to settings_path
  end

  def update_shipping_address
    @shipping_address = UpdateAddressService.new.call(params, current_user)
    @billing_address = current_user.billing_address || BillingForm.new

    return render :edit unless @shipping_address.errors.empty?

    redirect_to settings_path
  end

  def assign_flash(updated, entity)
    flash[:notice] = updated ? t("settings.updated_#{entity.downcase}") : t("settings.mistake_update_#{entity.downcase}")
  end
end

app/views/users/edit.haml
%main.container
  .row
    .col-sm-4
      %h1.general-title-margin
        =t('settings.title')
    .col-sm-4.text-center
      #avatar{ class: 'img-circle', ondragover: "allowDrop(event)", ondrop: "drop(event)"}
        = image_tag(user_cover(current_user), alt: 'user-img', class: 'img-circle user-size inlide-block')
        = form_with  url: settings_url, method: :patch, id: 'avatar_form', remote: true do |f|
          = f.hidden_field :new_avatar, value: nil, id: 'user_avatar'
          = f.button 'update avatar', hidden: true
      #overlay
        .cv-spinner
          %span.spinner
    .col-sm-4.text-center
      %h3.general-subtitle.mt-0
        = I18n.t('settings.avatar_icons')
      %br
      - current_user.user_images.each do |image|
        = image_tag(image.image_url, height: "69", ondragstart: "drag(event)", alt: 'user-img', id: 'avatar_icon', value: image.id, draggable: true, class: 'img-circle user-image-size inlide-block avatar')
  %ul.nav.clearfix.mb-20(role="tablist")
    %li.tab-item.active(role="presentation")
      %a.tab-link(aria-controls="address" data-toggle="tab" href="#address" role="tab")
        =t('settings.adress_tag')
    %li.tab-item(role="presentation")
      %a.tab-link(aria-controls="privacy" data-toggle="tab" href="#privacy" role="tab")
        =t('settings.privacy_tag')
  .tab-content
    #address.tab-pane.fade.in.active.general-main-wrap(role="tabpanel")
      .hidden-xs.hidden-sm
        .row
          .col-md-5
            %h3.general-subtitle.mt-0
              =t('settings.billing_address')
          .col-md-5.col-md-offset-1
            %h3.general-subtitle.mt-0
              =t('settings.shipping_address')
      .row
        .col-md-5.mb-40
          .visible-xs.visible-sm
            %h3.general-subtitle.mt-0
              =t('settings.billing_address')
          = simple_form_for @billing_address, as: :billing_address, url: settings_url, id: 'form_id', method: :patch,
            defaults: { input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' },
            label_html: { class: 'control-label input-label' } }, validate: true do |billing|
            = render partial: 'address/form_address', locals: { f: billing, type: 'billing_address' }
            = billing.button :submit, t('settings.save'), wrapper_html: { class: 'text-center general-text-align'}, input_html: { class: 'btn btn-default' }
        .col-md-5.col-md-offset-1.mb-25
          .visible-xs.visible-sm
            %h3.general-subtitle.mt-0
              =t('settings.shipping_address')
          = simple_form_for(@shipping_address, as: :shipping_address, url: settings_url, validate: true, method: :patch,
            defaults: { input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' },
            label_html: { class: 'control-label input-label' } }) do |shipping|
            = render partial: 'address/form_address', locals: { f: shipping, type: 'shipping_address' }
            = shipping.button :submit, t('settings.save'), wrapper_html: { class: 'text-center general-text-align'}, input_html: { class: 'btn btn-default' }
    #privacy.tab-pane.fade(role="tabpanel")
      .row.mb-60
        .col-sm-5
          %p.in-gold-500.font-18.mb-25
            =t('settings.email')
            = simple_form_for(current_user, as: :email_form, url: settings_url, method: :patch,
              defaults: { wrapper_html: { class: 'form-group mb-35 general-form-md' },
              label_html: { class: 'control-label input-label' } }) do |f|
              = f.input :email, label: t('quick_registration.login.enter_email'), placeholder: t('quick_registration.login.enter_email')
              = f.button :submit, t('settings.save'), wrapper_html: { class: 'general-text-align btn btn-default mb-35' }
          %p.in-gold-500.font-18.mb-25.pt-30
            =t('settings.avatar')
            = simple_form_for(current_user, as: :upload_image, url: settings_url, method: :patch,
              defaults: { wrapper_html: { class: 'form-group mb-35 general-form-md' },
              label_html: { class: 'control-label input-label' } }) do |f|
              = f.input :image, as: :file, input_html: { onchange: 'readURL(this)' }
              = f.button :submit, t('settings.save'), wrapper_html: { class: 'general-text-align btn btn-default mb-35' }
        .col-sm-5.col-sm-offset-1
          %p.in-gold-500.font-18.mb-25
            =t('settings.password')
          = simple_form_for(current_user, as: :password_form, url: settings_url, method: :patch, html: { class: 'divider-lg-bottom' },
            defaults: { wrapper_html: { class: 'general-form-md pb-25' },
            input_html: { class: 'form-control' }, label_html: { class: 'control-label input-label' } }) do |f|
            = f.input :current_password, required: true, label: t('settings.old_password'), placeholder: t('settings.old_password')
            = f.input :password, required: true, label: t('settings.new_password'), placeholder: t('settings.new_password')
            = f.input :password_confirmation, required: true, label: t('settings.confirm_password'), placeholder: t('settings.confirm_password')
            = f.button :submit, t('settings.save'), class: 'btn btn-default mb-10', wrapper_html: { class: 'general-text-align' }
        .col-sm-12
          %p.in-gold-500.font-18.mb-25
            =t('settings.remove_account')
          = simple_form_for current_user, method: :delete, class: "general-form-md pb-25", url: registration_path(current_user) do |f|
            .general-settings-btn
              = f.submit t('settings.btn_remove_account'), class: "btn disabled mb-20", id: 'delete_account'
            .form-group.checkbox.general-settings-checkbox
              %label.font-weight-light.pl-0
                %input.checkbox-input{type: "checkbox", hidden: "true", id: 'enable_button'}
                %span.checkbox-icon
                  %i.fa.fa-check
                %span.checkbox-text
                  =t('settings.checkbox_remove_account')