config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions' }
  ActiveAdmin.routes(self)

  root 'books#index'

  resources :order_items, only: %i[create update destroy]
  resources :books, only: %i[show index]
  resources :reviews, only: :create
  resources :orders, only: %i[index show]
  resource :cart, only: :show

  get 'settings' => 'users#edit'
  patch 'settings' => 'users#update'
  patch 'coupons' => 'coupons#update'
  patch 'order_items' => 'order_items#update'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :booksAuthors, dependent: :destroy
  has_many :books, through: :booksAuthors

  validates :first_name, :last_name, presence: true

  def full_name
    first_name + ' ' + last_name
  end
end

app/models/billing_address.rb
class BillingAddress < Address
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: %i[finders slugged]

  has_many :books_authors, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :authors, through: :books_authors
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, through: :order_items

  belongs_to :category
end

app/models/books_author.rb
class BooksAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :books, dependent: :destroy
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery_service.rb
class DeliveryService < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :book

  mount_uploader :image, ImageUploader
end

app/models/order.rb
require 'aasm'
class Order < ApplicationRecord
  include AASM

  belongs_to :user
  has_one :delivery_service, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :credit_card, dependent: :destroy

  aasm :status, column: :status do
    state :in_progress, initial: true
    state :processing
    state :shipped
    state :delivered
    state :canceled

    event :to_processing do
      transitions from: :in_progress, to: :processing
    end

    event :to_shipped do
      transitions from: :processing, to: :shipped
    end

    event :to_delivered do
      transitions from: :shipped, to: :delivered
    end

    event :to_canceled do
      transitions from: :delivered, to: :canceled
    end
  end

  aasm :checkout, column: :checkout do
    state :address, initial: true
    state :delivery
    state :payment
    state :confirm
    state :complete

    event :to_delivery do
      transitions from: :address, to: :delivery
    end

    event :to_payment do
      transitions from: :delivery, to: :payment
    end

    event :to_confirm do
      transitions from: :payment, to: :confirm
    end

    event :to_complete do
      transitions from: :confirm, to: :complete
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :book
  belongs_to :order

  validates :quantity, numericality: { greater_than: 0 }
end

app/models/review.rb
class Review < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :book

  validates :book_id, presence: true
  validates :user_id, presence: true
  validates :body, presence: true
  validates :title, presence: true

  aasm column: :status do
    state :unapproved, initial: true
    state :approved

    event :to_approve do
      transitions from: :unapproved, to: :approved
    end

    event :to_unapprove do
      transitions from: :approved, to: :unapproved
    end
  end
end

app/models/shipping_address.rb
class ShippingAddress < Address
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_images, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).or(where(email: auth.info.email)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz')
      user.name = auth.info.name
      user.avatar = auth.info.image
    end
  end
end

app/models/user_image.rb
class UserImage < ApplicationRecord
  belongs_to :user

  mount_uploader :image, UserImageUploader
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  BOOKS_PER_PAGE = 12
  include Pagy::Backend
  decorates_assigned :book
  before_action :assign_variables, only: :index

  def index
    @pagy, @books = pagy(BooksQuery.new.call(params, @current_filter), items: BOOKS_PER_PAGE)
  end

  def show
    @book = Book.friendly.find(params[:id])
  end

  def books_params
    params.permit(:date_range, :max_price, :category, :selection, :untill_date)
  end

  private

  def assign_variables
    assign_date_variables
    @maximum_price ||= Book.maximum(:price)
    @minimum_price ||= Book.minimum(:price)
    @price = books_params[:max_price] || @maximum_price
    @authors = params[:author_ids] || []
    @category = books_params[:category]
    sort_filter = books_params[:selection]
    @current_filter = BooksQuery::FILTERS.values.include?(sort_filter) ? sort_filter : BooksQuery::FILTERS[:created_at_desc]
  end

  def assign_date_variables
    time_now = Time.zone.now.strftime('%Y/%m/%d').to_s
    @date_range = books_params[:date_range] || time_now + ' ' + time_now
    @range = books_params[:date_range] || time_now
    @untill_date = books_params[:untill_date] || time_now
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  attr_reader :items, :order
  def show
    @items = OrderItemsService.new(current_user, session[:guest_items]).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include BooksHelper
  include CartsHelper

  def items_quantity
    order = current_user ? current_order : nil
    quantity = ItemsQuantityService.new.call(session[:guest_items], current_user, order)
    session[:guest_items].clear if current_user && session[:guest_items]
    quantity
  end
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend

  def book_cover(book)
    book.images.first_or_initialize.image.url
  end

  def user_cover(user)
    user.avatar || ActionController::Base.helpers.asset_path('user/default.png')
  end

  def no_books_image
    ActionController::Base.helpers.asset_path('fallback/no_books.jpg')
  end

  def categories
    Category.all
  end

  def all_books_quantity
    Book.all.count
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def order_summary
    order = current_user ? current_order : nil
    SummaryService.new.call(current_user, session[:guest_items], order)
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def alert_class(string)
    string == I18n.t('flash.alert') ? 'alert-danger' : 'alert-success'
  end
end

app/views/carts/partials/_cart_empty.haml
%h2.text-center.text-bold
  = I18n.t('order_items.empty_cart')

app/views/carts/partials/_cart_form.haml
.visible-xs
  = simple_form_for cart_path, method: :patch do |f|
    - @items.each do |book, quantity|
      = render partial: 'carts/partials/cart_item_xs', locals: {f: f, book: book, quantity: quantity}
.hidden-xs
  %table.table.table-hover
    %tr.no-hover
      %th.col-pic.pl-0
        %span.in-grey-600
          =t('cart.product')
      %th.col-title
      %th.col-price
        %span.in-grey-600
          = t('cart.price')
      %th.col-quantity
        %span.in-grey-600
          = t('cart.quantity')
      %th.col-total
        %span.in-grey-600
          = t('cart.subtotal')
      %th.col-close
    -# = render partial: 'carts/partials/cart_empty'
    = simple_form_for cart_path, method: :patch do |f|
      - @items.each do |book, quantity|
        = render partial: 'carts/partials/cart_item', locals: {f: f, book: book, quantity: quantity}
.general-order-wrap
  .row.text-center
    = render partial: 'carts/partials/summary'
    = link_to t('cart.checkout'), books_path, class: 'btn btn-default mb-20'

app/views/carts/partials/_cart_item.haml
%tr
  %td
    .general-img-wrap-table
      = image_tag( book_cover(book), alt: 'design-book', class: 'cart-img-shadow pull-left')
  %td
    %p.title
      = link_to book.title, book_path(book)
  %td
    %span.font-16.in-gold-500
      = t('book.price', price: book.price)
  %td
    .input-group
      = link_to order_items_path(book_id: book.id, value: quantity.to_i - 1), remote: true, method: :patch, class: 'input-link minus-book' do
        %i.fa.fa-minus.line-heaght-40
      = f.text_field :quantity, name: book.id, value: "#{quantity}",remote: true, min: 1, readonly: true, class: 'form-control quantity-input book-quantity-js'
      = link_to order_items_path(book_id: book.id, value: quantity.to_i + 1), method: :patch, class: 'input-link plus-book' do
        %i.fa.fa-plus.line-heaght-40
  %td
    %span.font-16.in-gold-500.items_total_price
      = t('book.price', price: ('%.2f' % (book.price*quantity.to_i)))
  %td
    = link_to order_item_path(book.id), method: :delete, class: 'close general-cart-close', 'aria-label': 'Close' do
      %span(aria-hidden='true') ×

app/views/carts/partials/_cart_item_xs.haml
.general-cart-item.divider-lg-bottom
  %button.close.general-cart-close(aria-label='Close' type="button")
    %span(aria-hidden="true") ×
  .general-img-wrap-table
    = image_tag( book_cover(book), alt: 'design-book', class: 'cart-img-shadow')
  %p.title
    = link_to book.title, book_path(book)
  %table.table
    %tr
      %td
        %span.in-grey-600
          = t('cart.price')
      %td
        %span.font-16.in-gold-500
          = t(:'book.price', price: book.price)
    %tr
      %td.vertical-middle
        %span.in-grey-600
          = t('cart.quantity')
      %td
        .input-group
          = link_to order_items_path(book_id: book.id, value: quantity.to_i - 1), remote: true, method: :patch, class: "input-link minus" do
            %i.fa.fa-minus.line-heaght-40
          = f.text_field :quantity, name: book.id, value: "#{quantity}",remote: true, min: 1, readonly: true, class: "form-control quantity-input book-quantity-js"
          = link_to order_items_path(book_id: book.id, value: quantity.to_i + 1), method: :patch, class: "input-link plus" do
            %i.fa.fa-plus.line-heaght-40
    %tr
      %td
        %span.in-grey-600
          = t('cart.subtotal')
      %td
        %span.font-16.in-gold-500
          = t('book.price', price: order_summary[:subtotal])

app/views/carts/partials/_coupon.haml
.col-sm-4
  .input-group.general-input-group
    %label.input-label
      = t('cart.coupon_button')
    = f.text_field :key, placeholder: I18n.t('cart.coupon_field'), class: 'orm-control mb-30'
    %div
      =f.submit I18n.t('cart.coupon_button'), class: 'btn btn-primary mr-5 mb-15'

app/views/carts/partials/_summary.haml
.row.res-mr-200.text-center.general-text-right
  %p.in-gold-500.font-18
    = t('cart.summary')
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16
          = t('cart.subtotal')
      %td
        %p.font-16
          = t('book.price', price: order_summary[:subtotal])
    %tr
      %td
        %p.font-16
          =t('cart.coupon')
      %td
        %p.font-16
          = t('book.price', price: order_summary[:coupon])
    %tr
      %td
        %strong.font-18
          = t('cart.order_total')
      %td
        %strong.font-18
          = t('book.price', price: order_summary[:total])

app/views/carts/show.haml
%main.container.general-main-wrap.h-100
  %h1.general-title-margin
    = I18n.t('cart.title_cart')
  = render partial: (@items.present? ? 'carts/partials/cart_form' : 'carts/partials/cart_empty')