config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions' }
  ActiveAdmin.routes(self)

  root 'books#index'

  resources :order_items, only: %i[create update destroy]
  resources :books, only: %i[show index]
  resources :reviews, only: :create
  resources :orders, only: %i[index show]
  resource :cart, only: :show

  get 'settings' => 'users#edit'
  patch 'settings' => 'users#update'
  patch 'coupons' => 'coupons#update'
  patch 'order_items' => 'order_items#update'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :booksAuthors, dependent: :destroy
  has_many :books, through: :booksAuthors

  validates :first_name, :last_name, presence: true

  def full_name
    first_name + ' ' + last_name
  end
end

app/models/billing_address.rb
class BillingAddress < Address
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: %i[finders slugged]

  has_many :books_authors, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :authors, through: :books_authors
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, through: :order_items

  belongs_to :category
end

app/models/books_author.rb
class BooksAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :books, dependent: :destroy
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery_service.rb
class DeliveryService < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :book

  mount_uploader :image, ImageUploader
end

app/models/order.rb
require 'aasm'
class Order < ApplicationRecord
  include AASM

  belongs_to :user
  has_one :delivery_service, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :credit_card, dependent: :destroy

  aasm :status, column: :status do
    state :in_progress, initial: true
    state :processing
    state :shipped
    state :delivered
    state :canceled

    event :to_processing do
      transitions from: :in_progress, to: :processing
    end

    event :to_shipped do
      transitions from: :processing, to: :shipped
    end

    event :to_delivered do
      transitions from: :shipped, to: :delivered
    end

    event :to_canceled do
      transitions from: :delivered, to: :canceled
    end
  end

  aasm :checkout, column: :checkout do
    state :address, initial: true
    state :delivery
    state :payment
    state :confirm
    state :complete

    event :to_delivery do
      transitions from: :address, to: :delivery
    end

    event :to_payment do
      transitions from: :delivery, to: :payment
    end

    event :to_confirm do
      transitions from: :payment, to: :confirm
    end

    event :to_complete do
      transitions from: :confirm, to: :complete
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :book
  belongs_to :order

  validates :quantity, numericality: { greater_than: 0 }
end

app/models/review.rb
class Review < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :book

  validates :book_id, presence: true
  validates :user_id, presence: true
  validates :body, presence: true
  validates :title, presence: true

  aasm column: :status do
    state :unapproved, initial: true
    state :approved

    event :to_approve do
      transitions from: :unapproved, to: :approved
    end

    event :to_unapprove do
      transitions from: :approved, to: :unapproved
    end
  end
end

app/models/shipping_address.rb
class ShippingAddress < Address
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_images, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).or(where(email: auth.info.email)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz')
      user.name = auth.info.name
      user.avatar = auth.info.image
    end
  end
end

app/models/user_image.rb
class UserImage < ApplicationRecord
  belongs_to :user

  mount_uploader :image, UserImageUploader
end

app/helpers/application_helper.rb
module ApplicationHelper
  include BooksHelper
  include CartsHelper

  def items_quantity
    order = current_user ? current_order : nil
    quantity = ItemsQuantityService.new.call(session[:guest_items], current_user, order)
    session[:guest_items].clear if current_user && session[:guest_items]
    quantity
  end
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend

  def book_cover(book)
    book.images.first_or_initialize.image.url
  end

  def user_cover(user)
    user.avatar || ActionController::Base.helpers.asset_path('user/default.png')
  end

  def no_books_image
    ActionController::Base.helpers.asset_path('fallback/no_books.jpg')
  end

  def categories
    Category.all
  end

  def all_books_quantity
    Book.all.count
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def order_summary
    order = current_user ? current_order : nil
    SummaryService.new.call(current_user, session[:guest_items], order)
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def alert_class(string)
    string == I18n.t('flash.alert') ? 'alert-danger' : 'alert-success'
  end
end

app/views/address/_form_address.haml
= f.input :type, :as => :hidden, :input_html => { :value => "#{type}" }
= f.input :first_name, label: t('settings.first_name'), placeholder: t('settings.first_name')
= f.input :last_name, label: t('settings.last_name'), placeholder: t('settings.last_name')
= f.input :address, label: t('settings.adress_area'), placeholder: t('settings.adress_area')
= f.input :city, label: t('settings.city'), placeholder: t('settings.city')
= f.input :zip, label: t('settings.zip'), placeholder: t('settings.zip')
= f.input :country, :collection => %w[Ukraine Germane USA UK], label: t('settings.country'), placeholder: t('settings.country')
= f.input :phone, label: t('settings.phone'), placeholder: t('settings.phone')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "UTF-8"}/
    %meta{content: "width=device-width", name: "viewport"}/
    %title Bookstore
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render partial: 'layouts/partials/header'
    .container
      =render partial: 'layouts/partials/flash_message'
    = yield
    =render partial: 'layouts/partials/footer'

app/views/layouts/partials/_flash_message.haml
- flash.each do |name, message|
  %div.alert.text-center{ class: "alert-#{name} #{alert_class(name)}" }
    = message

app/views/layouts/partials/_footer.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            %a.nav-link{href: "#"} Home
          %li
            %a.nav-link{href: "#"} Shop
          %li
            %a.nav-link{href: "#"} Orders
          %li
            %a.nav-link{href: "#"} Settings
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{"aria-hidden" => "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{"aria-hidden" => "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{"aria-hidden" => "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{"aria-hidden" => "true"}

app/views/layouts/partials/_header.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{"data-target" => "#navbar", "data-toggle" => "collapse", type: "button"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Bookstore', root_path, class: 'navbar-brand'
    = link_to cart_path, class: "shop-link pull-right visible-xs" do
      %span.shop-icon
        %span.shop-quantity
          = items_quantity
    = link_to cart_path, class: "shop-link pull-right hidden-xs" do
      %span.shop-icon
        %span.shop-quantity
          = items_quantity
    #navbar.navbar-collapse.collapse.pl-30{"aria-expanded": "false"}
      .visible-xs
        %button.close{"aria-label": "Close", type: "button"}
          %span{"aria-hidden": "true"} ×
        %ul.nav.navbar-nav
          %li
            = link_to t('header.home'), root_path
          %li
            %a{"aria-controls": "menu", "aria-expanded": "false", "data-toggle": "collapse", href: "#menu", type: "button"}
              = t('header.shop')
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{"aria-expanded" => "false"}
              - categories.each do |category|
                %li
                  = link_to category.title, books_path(category: category.friendly_id)
          - if user_signed_in?
            %li.dropdown
              %a{ href: '#'}
                = current_user.email
              %ul.dropdown-menu.dropdown-content
                %li
                  = link_to t('header.settings'), settings_path
                %li.divider{role: "separator"}
                %li
                  = link_to t('header.logout'), destroy_user_session_path, method: :delete
          - unless user_signed_in?
            %li
              = link_to t('header.sign_up'), new_user_registration_path, class: 'navbar-link'
            %li
              = link_to t('header.login'), new_user_session_path, class: 'navbar-link'
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            = link_to t('header.home'), root_path
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
              = t('header.shop')
            %ul.dropdown-menu
              - categories.each do |category|
                %li
                  = link_to category.title, books_path(category: category.friendly_id)
          - if user_signed_in?
            %li.dropdown
              %a{ href: '#'}
                = current_user.email
              %ul.dropdown-menu.dropdown-content
                %li
                  = link_to t('header.settings'), settings_path
                %li.divider{role: "separator"}
                %li
                  = link_to t('header.logout'), destroy_user_session_path, method: :delete
          - unless user_signed_in?
            %li
              = link_to t('header.sign_up'), new_user_registration_path, class: 'navbar-link'
            %li
              = link_to t('header.login'), new_user_session_path, class: 'navbar-link'